// <auto-generated />
namespace FIVESTARVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resident_todelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resident_todelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201909011040583_resident_todelete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
