// <auto-generated />
namespace FIVESTARVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_room_support : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_room_support));
        
        string IMigrationMetadata.Id
        {
            get { return "201906010127450_remove_room_support"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
